Blog/urls.py
from django.urls import path
from .views import *

urlpatterns = [
        path("about/", about, name= "About"),
        path("contacto/", contacto, name= "contacto"),

        path('login/', iniciar_sesion, name='login_usuario'),
        path('logout/', cerrar_sesion, name='logout_usuario'),
        path('editar_usuario/', editar_usuario, name='editar_usuario'),
        path('perfil/', editar_usuario, name='perfil_usuario'),
        path('registro/', registrarse, name='registro'),

        path("post_list/", post_list, name= "post_list"),
        path("post/<int:pk>/", post_detail, name= "post_detail"),
        path('post/<int:pk>/comment/', add_comment_to_post, name='add_comment_to_post'),
        path('post/create/', create_post, name='create_post'),
        path('user_posts/', user_posts, name='user_posts'),
        path('delete_post/<int:pk>/', delete_post, name='delete_post'),
        path('post/<int:pk>/edit/', edit_post, name='edit_post'),
        path("publi/", posteo, name= "posteo"),

        path('admin_dashboard/', admin_dashboard, name='admin_dashboard'),
        path('admin/edit_post/<int:pk>/', admin_edit_post, name='admin_edit_post'),
        path('admin/delete_post/<int:pk>/', admin_delete_post, name='admin_delete_post'),
        path('post_comments/<int:pk>/', post_comments, name='post_comments'),
        path('delete_comment/<int:pk>/', delete_comment, name='delete_comment'),

        path('agregar_avatar/', agregar_avatar, name='agregar_avatar'),
       # path('avatar/', ver_avatar, name='ver_avatar'),
        #path('avatar_no_encontrado/', avatar_no_encontrado, name='avatar_no_encontrado'),
        #path('eliminar_avatar/', eliminar_avatar, name='eliminar_avatar'),


        path('', inicio, name='Home'),

        
]

blog_folch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
     path('blog/', include("Blog.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Blog/models.py
from django.db import models
from django.contrib.auth.models import User


    
class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    
class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    image = models.ImageField(upload_to='post_images/', null=True, blank=True)
    date_posted = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Comment by {self.author} on {self.post.title}'
    
class Avatar(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="avatares", null=True, blank=True)

    def __str__(self):
        return f"Avatar de {self.usuario.username}"
    
    

Blog/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from .models import *

class RegistroForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)


class RegistroUsuario(UserCreationForm):

    class Meta:
        model = User
        fields = ["username", "first_name", "last_name",  "email", "password1", "password2"]

class EditarUsuarioForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

###POST
###POST
###POST

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']

class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ['name']

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'image']  # Puedes quitar 'image' si no deseas que se agregue una imagen al crear una publicación

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

class PostUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']

class AvatarForm(forms.ModelForm):
    class Meta:
        model = Avatar
        fields = ['imagen']

## EDITAR PERFIL PARA NUEVA PAGINA DE EDICIONDEPERFIL

class EditarPerfilForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


'''
class AvatarForm(forms.ModelForm):
    class Meta:
        model = Avatar
        fields = ['imagen']
        labels = {'imagen': 'Avatar'}
        help_texts = {'imagen': 'Ya tienes un avatar. Puedes cargar uno nuevo si lo deseas.'}
'''

Blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.contrib import messages
from django.http import HttpResponse
from django.http import HttpResponseNotFound
from .models import *
from .forms import *

# Create your views here.
def inicio(request):

    return render(request, "inicio.html", {"mensaje": "Bienvenido a Ñami"})

def contacto(request):

    return render(request, "contacto.html", {"mensaje": "Contacta con nosotros"})

def about(request):

    return render(request, "about.html", {"mensaje": "Quienes Somos?"})

def posteo(request):

    return render(request, "posteo.html", {"mensaje": "post"})

'''
def iniciar_sesion(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return render(request, "inicio.html", {"mensaje":f"Bienvenido {username}"})
            else:
                return render(request, "inicio.html", {"mensaje":"Credenciales Incorrectas"})
    else:
        form = LoginForm()
        return render(request, 'login_usuario.html', {'form': form})

        
def registrar_usuario(request):
    if request.method == 'POST':
        form = RegistroForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return render(request, "inicio.html", {"mensaje": "El usuario ha sido creado con éxito"}) 
    else:
        form = RegistroForm()
    return render(request, 'registro.html', {'form': form})
    
'''
#### LOGIN LOGOUT REGISTRO ####
#### LOGIN LOGOUT REGISTRO ####
#### LOGIN LOGOUT REGISTRO ####

def iniciar_sesion(request):
    if request.method == "POST":
        formulario = AuthenticationForm(request, data = request.POST) #almacena la informacion que se ha puesto en el form
        if formulario.is_valid():
            info_dic = formulario.cleaned_data #convierte la info del form a un diccionario de python
            usuario = authenticate(username=info_dic["username"], password=info_dic["password"])
            if usuario is not None: #que el usuario existe!!!
                login(request, usuario)
                return render(request, "inicio.html", {"mensaje":f"Bienvenido {usuario}"})
        else:
            return render(request, "inicio.html", {"mensaje":"Credenciales Incorrectas"})
    else:
        formulario = AuthenticationForm()
    return render(request, "usuario/login_usuario.html", {"formu":formulario})

def registrarse(request):

    if request.method == "POST":
        formulario = RegistroUsuario(request.POST)
        if formulario.is_valid():
            formulario.save() #crea el nuevo usuario
            return render(request, "inicio.html", {"mensaje":"El usuario ha sido creado con éxito."})
   
    else:
        formulario = RegistroUsuario()
    return render(request, "usuario/registro.html", {"formu":formulario})

@login_required
def cerrar_sesion(request):
    logout(request)
    return render(request, "inicio.html", {"mensaje": "Sesion Cerrada con éxito"})

@login_required
def editar_usuario(request):
    if request.method == 'POST':
        form = EditarUsuarioForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('Home')  # Redirigir a la página del perfil del usuario después de editar
    else:
        form = EditarUsuarioForm(instance=request.user)
    return render(request, 'usuario/editar_usuario.html', {'form': form})


### POST ###
### POST ###
### POST ###

def post_list(request):
    posts = Post.objects.all().order_by('-date_posted')
    return render(request, 'blog/post_list.html', {'posts': posts})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comments = Comment.objects.filter(post=post)
    return render(request, 'blog/post_detail.html', {'post': post, 'comments': comments})

@login_required
def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user  # Asigna el usuario actual como autor del comentario
            comment.save()
            return redirect('post_detail', pk=post.pk)  # Redirige al detalle de la publicación
    else:
        form = CommentForm()
    return render(request, 'blog/add_comment_to_post.html', {'form': form})

@login_required
def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user  # Asigna el usuario actual como autor del post
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/create_post.html', {'form': form})

@login_required
def user_posts(request):
    user_posts = Post.objects.filter(author=request.user)
    return render(request, 'blog/user_posts.html', {'user_posts': user_posts})


@login_required
def edit_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    
    # Verificar que el usuario actual sea el autor de la publicación
    if request.user != post.author:
        return redirect('post_detail', pk=pk)  # Redirigir a la página de detalles de la publicación si el usuario no es el autor
    
    if request.method == 'POST':
        form = PostUpdateForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('post_detail', pk=pk)  # Redirigir a la página de detalles de la publicación después de la edición
    else:
        form = PostUpdateForm(instance=post)
    
    return render(request, 'blog/edit_post.html', {'form': form, 'post': post})

@login_required
def delete_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        post.delete()
        return redirect('user_posts')  # Redirige a la vista de las publicaciones del usuario
    return redirect('Home')  # Redirige a otra página si no se utiliza el método POST

##ADMINISTRADORES
##ADMINISTRADORES
##ADMINISTRADORES

@login_required
def admin_dashboard(request):
    user_is_admin = check_admin_user(request.user)
    posts = Post.objects.all()
    return render(request, 'admin/admin_dashboard.html', {'user_is_admin': user_is_admin, 'posts': posts})

def check_admin_user(user):
    administradores = Group.objects.get(name='Administradores')
    return administradores in user.groups.all()

@login_required    
def admin_edit_post(request, pk):
    if check_admin_user(request.user):
        post = get_object_or_404(Post, pk=pk)
        if request.method == 'POST':
            form = PostUpdateForm(request.POST, instance=post)
            if form.is_valid():
                form.save()
                return redirect('admin_dashboard')
        else:
            form = PostUpdateForm(instance=post)
        return render(request, 'admin/admin_edit_post.html', {'form': form})
    else:
        return redirect('Home')
    
@login_required
def admin_delete_post(request, pk):
    # Verificar si el usuario actual pertenece al grupo de administradores
    if check_admin_user(request.user):
        post = Post.objects.get(pk=pk)
        post.delete()
        return redirect('admin_dashboard')
    else:
        # Si el usuario no es un administrador, redirigir a otra página o mostrar un mensaje de error
        return render(request, 'inicio.html')
    

@login_required
def post_comments(request, pk):
    # Verificar si el usuario actual pertenece al grupo de administradores
    administradores = Group.objects.get(name='Administradores')
    if administradores not in request.user.groups.all():
        return render(request, 'inicio.html', {'message': 'No tienes permiso para acceder a esta página.'})

    post = get_object_or_404(Post, pk=pk)
    comments = Comment.objects.filter(post=post)
    return render(request, 'admin/post_comments.html', {'post': post, 'comments': comments})

@login_required
def delete_comment(request, pk):
    # Verificar si el usuario actual pertenece al grupo de administradores
    if check_admin_user(request.user):
        comment = get_object_or_404(Comment, pk=pk)
        comment.delete()
        # Redirigir de vuelta a la página de comentarios después de eliminar el comentario
        return redirect('post_comments', pk=comment.post.pk)
    else:
        # Si el usuario no es un administrador, redirigir a otra página o mostrar un mensaje de error
        return render(request, 'inicio.html')
    

####AVATAR
####AVATAR
####AVATAR
'''    
@login_required
def agregar_avatar(request):
    if request.method == "POST":
        formulario = AvatarForm(request.POST, request.FILES)
        if formulario.is_valid():
            avatar = formulario.save(commit=False)
            avatar.usuario = request.user
            avatar.save()
            return redirect('Home')  # Redirige a la página de inicio después de agregar el avatar
    else:
        formulario = AvatarForm()
    return render(request, "avatar/nuevo_avatar.html", {"formu": formulario})


@login_required
def agregar_avatar(request):
    usuario = request.user
    try:
        avatar_existente = Avatar.objects.get(usuario=usuario)
        if request.method == "POST":
            formulario = AvatarForm(request.POST, request.FILES, instance=avatar_existente)
        else:

Blog/templates/usuario/editar_usuario.html
{% extends "padre.html" %}
{% load static %}
{% block contenido %}
<!DOCTYPE html>
<html lang="en">
    <header class="py-5 bg-light border-bottom mb-4">
        <div class="container">
            <div class="text-center my-5">
                <h1 class="fw-bolder">Edita tu usuario!!</h1>
                <p class="lead mb-0">modifica tu informacion para conocerte mejor!</p>
            </div>
        </div>
    </header>
<body>
    <h1>Editar Usuario</h1>
    <form id="edit-user-form" action="{% url 'editar_usuario' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_first_name">Nombre:</label>
            <input type="text" class="form-control" id="id_first_name" name="first_name" value="{{ user.first_name }}" required>
        </div>
        <div class="form-group">
            <label for="id_last_name">Apellido:</label>
            <input type="text" class="form-control" id="id_last_name" name="last_name" value="{{ user.last_name }}" required>
        </div>
        <div class="form-group">
            <label for="id_email">Correo electrónico:</label>
            <input type="email" class="form-control" id="id_email" name="email" value="{{ user.email }}" required>
        </div>
        <button type="button" class="btn btn-primary" onclick="confirmSaveChanges()">Guardar Cambios</button>
    </form>
    <script>
        function confirmSaveChanges() {
            if (confirm("¿Estás seguro de que quieres guardar los cambios en tu perfil?")) {
                document.getElementById("edit-user-form").submit();
            }
        }
    </script>
</body>
</html>
{% endblock %}

Blog/templates/usuario/login_usuario.html
{% extends "padre.html" %}
{% load static %}
{% block contenido %}

{{mensaje}}

<div style="display: flex; justify-content: center; align-items: flex-start; padding: 20px;">
    <div style="width: 70%; padding-right: 20px;">
        <h1 style="font-size: 36px; color: #333; font-family: 'Arial', sans-serif;">Iniciar sesión</h1>
        <form method="post" style="margin-top: 20px;">
            {% csrf_token %}
            <div class="mb-3">
                {{ formu.username.label_tag }}
                {{ formu.username }}
            </div>
            <div class="mb-3">
                {{ formu.password.label_tag }}
                {{ formu.password }}
            </div>
            <button type="submit" class="btn btn-primary">Iniciar sesión</button>
        </form>
        <p>¿Aun no te registras? <a href="{% url 'registro' %}">Registrarse</a>.</p>
    </div>
    <div style="width: 30%; border: 1px solid #ccc; padding: 20px;">
        <h2 style="font-size: 24px; color: #333; font-family: 'Arial', sans-serif;">Side Widget</h2>
        <div class="card mb-4">
            <div class="card-body">You can put anything you want inside of these side widgets. They are easy to use, and feature the Bootstrap 5 card component!</div>
        </div>
    </div>
</div>
    
{% endblock %}

Blog/templates/usuario/perfil_usuario.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Perfil de Usuario</title>
    <style>
        .profile-container {
            display: flex;
            justify-content: space-between;
            flex-wrap: wrap;
        }
        .profile-info {
            width: 100%;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
            margin-bottom: 20px;
        }
        .avatar-container {
            width: 100%;
            padding: 30px;
            border: 2px solid #ccc;
            border-radius: 5px;
        }
        .avatar-container img {
            max-width: 200px;
            max-height: 200px;
        }
    </style>
</head>
<body>
    <h1>Perfil de Usuario</h1>
    <div class="profile-container">        
        <div class="avatar-container">
            <img src="{{user.avatar_set.last.imagen.url}}" alt="Avatar">
            <h2>Avatar</h2>
            <li>
                <form method="get" action="{% url 'agregar_avatar' %}">
                    <button type="submit" class="nav-link active" aria-current="page">
                        Cambiar Avatar Imagen
                    </button>
                </form>
            </li>
        </div>
        <div class="profile-info">
            <h2>Información de Usuario</h2>
            <p><strong>Usuario:</strong> {{ user.username }}</p>
            <p><strong>Nombre:</strong> {{ user.first_name }}</p>
            <p><strong>Apellido:</strong> {{ user.last_name }}</p>
            <p><strong>Correo:</strong> {{ user.email }}</p>
            <form method="post" action="{% url 'editar_usuario' %}">
                {% csrf_token %}
                <button type="submit">Editar</button>
            </form>
        </div>
    </div>
</body>
</html>

Blog/templates/usuario/registro.html
{% extends "padre.html" %}
{% load static %}
{% block contenido %}



{{mensaje}}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro</title>
</head>
<body>
    <h2>Registro</h2>
    <form method="post">
        {% csrf_token %}
        {{ formu.as_p }}
        <input type="submit" value="Register">
    </form>
</body>
</html>
{% endblock %}